# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('naijalogos_office', '0002_auto_20161217_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorremittance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
