# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijalogos_office', '0003_auto_20161225_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vendorremittance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
